# Generated by Django 4.1.3 on 2023-08-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentajetapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbooking',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
