# Generated by Django 4.1.3 on 2023-08-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentajetapi', '0002_flightbooking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='uid',
            field=models.CharField(default='', max_length=200),
        ),
    ]
