# Generated by Django 4.1.3 on 2023-08-05 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentajetapi', '0003_customer_uid'),
        ('rentajetapi', '0003_remove_flightbooking_price'),
    ]

    operations = [
    ]
